### ISSUE TITLE
Lightning 1.6 Release

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#11890]
# List of tasks to complete the 1.6.0 Release

Release date: TBA
Feature freeze date: TBA

## Up to Feature Freeze

[List of 1.6 milestones](https://github.com/PyTorchLightning/pytorch-lightning/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.6)

- [ ] Stable Accelerator API #9932 
- [ ] Unify Checkpointing conventions #11429

(list incomplete)

## Before or after Feature Freeze

- [ ] Documentation updates
    - [ ] Update all pages to the latest accelerator/strategy/devices syntax
    - [ ] Documentation check (typos, new features, etc. (e.g.  #11739))
- [ ] Create the release blog post
- [ ] Changelog check
- [ ] Create release notes

(list incomplete)

Feel free to edit this page!

cc @justusschock @awaelchli @rohitgr7 @borda

**Comment by carmocca** [comment]
Closing this in favor of issue planning.

Ping me if you have any questions or you want to add an item!
