### ISSUE TITLE
Add testing with PyTorch 1.11 on GPUs in CI

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#12955]
## 🚀 Feature
We've decided to have testing with both PyTorch LTS and stable release (1.8 and 1.11 as of now) in CI, and we've already seen some issues arose while trying to enable it in #12373.

### TODO
Known issues with PL with PyTorch 1.11

- [x] #12846
- [x] #12860
- [ ] Fix an issue with fitting a model initialised in init_meta_context #12870
- [x] Fix an issue with DDP comm tests with some newer PyTorch versions #12878
- [ ] Fix an issue with inference mode with FSDP

### Motivation
To test new features, e.g. meta init and native FSDP, in CI that are only available in newer PyTorch versions.

### Pitch
Use the following image:
```
pytorchlightning/pytorch_lightning:base-cuda-py3.7-torch1.11
```

### Alternatives
n/a

### Additional context
n/a

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @carmocca @akihironitta @borda

**Comment by akihironitta** [comment]
@Borda Would it be an option to have PyTorch 1.12 (nightly) testing, too? For example, #12985 needs 1.12 for adapting FSDP native.

> 1.11 FSDP seems to be broken in various ways, with state_dict saving/loading issues + no mixed precision. So many fixes have come out for 1.12 (nightly) that no user really should be using 1.11, and be using 1.12 FSDP.

**Comment by SeanNaren** [comment]
@akihironitta I think starting with 1.11 is a good idea and seeing how CI time works. I'm scared to use 1.12 nightly in CI as it changes frequently (but I haven't run into compatibility issues).

**Comment by carmocca** [comment]
1.11 is fine (already released)

We removed nightly testing because it was too flaky, making everybody ignore the job. We only enable it when there's a release candidate upstream

**Comment by akihironitta** [comment]
Will be addressed in #12984.
