### ISSUE TITLE
fix typing in PL codebase - multiple PRs

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#5023]
## 🚀 Feature

add/fix typing in all PL codebase, this will yield in multiple PR as we prefer to split the work into smaller peace

### Additional context

in #5021  we introduced a new ignore list so after it is merged, take out a single ignored item and fix typing for that part 
> each item + its fix = one PR

### Sections

- [ ] `pytorch_lightning.callbacks.*` #7035
- [ ] `pytorch_lightning.core.*`  #7035
- [ ] `pytorch_lightning.accelerators.*`  #7035
- [ ] `pytorch_lightning.loggers.*` #7035
- [ ] `pytorch_lightning.logging.*` #7035
- [ ] `pytorch_lightning.metrics.*` <---| @hassiahk
- [ ] `pytorch_lightning.overrides.*`
- [ ] `pytorch_lightning.profiler.*`
- [ ] `pytorch_lightning.pt_overrides.*`
- [ ] `pytorch_lightning.plugins.*`  #7022
- [ ] `pytorch_lightning.root_module.*`
- [ ] `pytorch_lightning.trainer.*`
- [ ] `pytorch_lightning.distributed.*`
- [ ] `pytorch_lightning.tuner.*`
- [ ] `pytorch_lightning.utilities.*`
- [ ] `pl_examples.* by` <---| @janhenriklambrechts
- [ ] `benchmarks.*`
- [ ] `tests.*`

_This sections can be split even to smaller, most likely still stay per package/folder_

**Comment by janhenriklambrechts** [comment]
I am happy to start working on this

**Comment by edenlightning** [comment]
Thanks @janhenriklambrechts!

**Comment by hemildesai** [comment]
I'm also happy to help with this if extra hands are needed.

**Comment by Borda** [comment]
> I'm also happy to help with this if extra hands are needed.

Great! Let me know (here or slack) which section you want to take (or you can take just position of a section and update ignore accordingly)

**Comment by hemildesai** [comment]
> > I'm also happy to help with this if extra hands are needed.
> 
> Great! Let me know (here or slack) which section you want to take (or you can take just position of a section and update ignore accordingly)

@Borda I'll just start in the order mentioned in the issue with `callbacks`. Let me know which sections @janhenriklambrechts has taken so I don't clash.

**Comment by Borda** [comment]
> > Great! Let me know (here or slack) which section you want to take (or you can take just position of a section and update ignore accordingly)
> 
> @Borda I'll just start in the order mentioned in the issue with `callbacks`. Let me know which sections @janhenriklambrechts has taken so I don't clash.

Great, I fill you in the description so we keep track who took what part...

**Comment by hemildesai** [comment]
@Borda There will be issues with circular dependency imports when importing type hints for `Trainer`. One way to solve it is mentioned in https://www.stefaanlippens.net/circular-imports-type-hints-python.html.

To avoid [forward references](https://mypy.readthedocs.io/en/latest/kinds_of_types.html#class-name-forward-references), we'll have to add `from __future__ import annotations` but that only works for python versions gte `3.7`.

What do you suggest to resolve this? We can use forward references if we need to support versions less than `3.7` I guess.

**Comment by Borda** [comment]
Let me see, not sure about the right way to go...
One option may be what @tchaton tried `import pytorch_lightning ` and later use string-like annotations `"my_argument: "pytorch_lightning.Trainer"`

**Comment by hemildesai** [comment]
Yes

> "my_argument: "pytorch_lightning.Trainer"

Yes can definitely do this. Once support for Python versions less than `3.7` is dropped, we can change to using `from __future__ import annotations` and avoid using string annotations.

**Comment by Borda** [comment]
@hemildesai well having it not string would work better for cross-reference in IDE, right?

**Comment by hemildesai** [comment]
> @hemildesai well having it not string would work better for cross-reference in IDE, right?

I'm trying it in vscode and it seems to resolve the string annotations as well. Also, having non string annotations won't work for versions less than `3.7` so I think we'll have to go with string annotations till support for python3.6 is dropped.

**Comment by hassiahk** [comment]
I am more than happy to help as well :smile: . Let me know if I can start with the `metrics`.

**Comment by Borda** [comment]
@hemildesai @hassiahk@janhenriklambrechts how is it going? :]

**Comment by Borda** [comment]
@hemildesai I think that @tchaton had a hack about importing pl as a package and then put the full path in typing...
any other suggestion @akihironitta @ydcjeff ?

**Comment by akihironitta** [comment]
@hemildesai As you mentioned, we still support 3.6, so I think we could just use forward references (string-literal type hints) for now.

**Comment by hemildesai** [comment]
@Borda @akihironitta Yeah I used that in my PR - https://github.com/PyTorchLightning/pytorch-lightning/pull/5104
But there's an issue with building the docs. In order to fix that, I suggested a solution in that PR but that would mean that type hints won't be available in IDEs like VSCode. I'm just waiting for the resolution to my comment in that PR and then I can implement the necessary changes.

**Comment by hassiahk** [comment]
> @hemildesai @hassiahk@janhenriklambrechts how is it going? :]

@Borda, I am really sorry, will be a bit busy till the end of this month and can only work on this after that.

**Comment by akihironitta** [comment]
>@hemildesai I think that @tchaton had a hack about importing pl as a package and then put the full path in typing...

@Borda What do you mean by the full path? Something like `trainer: "pl.trainer.trainer.Trainer"`?

**Comment by edenlightning** [comment]
@Borda mind updating this?

**Comment by Borda** [comment]
> @Borda mind updating this with the current status?

@tchaton ?

**Comment by carmocca** [comment]
Closing in favor of #7037 which has more linked issues. I'll update the description there
