### ISSUE TITLE
ClusterEnvironment interface and improvements

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#6303]
## 🚀 Feature

In #5915 we started discussing what a good interface for the cluster environment could be and where it is headed in the future.
We should iterate on these ideas.

Some ideas / issues / refactors to discuss:

- [x] there is a small amount of code duplication.
- [x] Review #5102 and determine if interface needs changes
- [x] Add docs for all environments
- [x] Teardown logic: cluster environments that set environment variables (globally) should also be responsible for cleaning them up (#6942)
- [ ] Convert methods to proper setters/getters (#10103)
- [x] Consider renaming "creates_children". It is not clear if it means the environment within Lightning or the actual cluster. cc @borda @justusschock @awaelchli @akihironitta @rohitgr7 @tchaton @ananthsub #10339 
- [x] Move left over slurm logic in slurm connector to the slurm environment (#10622 #10615)

- [x] A `detect` method:

```python
# returns true if we can detect the cluster environment.
def detect():
    if ...
        return True
```

**Comment by leezu** [comment]
Trainer has a SLURM specific property. Should it be deprecated as part of the ClusterEnvironment interface improvements?

https://github.com/PyTorchLightning/pytorch-lightning/blob/8c0ea92af237542f5b36ae684543f871da829379/pytorch_lightning/trainer/properties.py#L176-L189

**Comment by awaelchli** [comment]
Hi, good observation. I would say the logic inside of it can and should definitely move into the cluster plugin. I would still keep the property as an easy way to access the cluster environment IF that is something users actually access (I have no idea).

**Comment by ananthsub** [comment]
> Consider renaming "creates_children". It is not clear if it means the environment within Lightning or the actual cluster. cc @ananthsub

Since it came up in #9389 - we need a consistent value here during the course of the job. relying on the mutable os.environ for instance can lead to surprising side effects. a naming nit would be to to rename this as `created_children` to be ultra clear that this either happened or didn't, as opposed to a continuous/ongoing behavior.

**Comment by carmocca** [comment]
@awaelchli is this done? can we close?

**Comment by awaelchli** [comment]
@carmocca there is one item open

> Convert methods to proper setters/getters

It came up in reviews that people were wondering why the methods are not properties. They are not properties because the plugins are meant to be customized by overriding them and in Lightning we have the strict rule to avoid decorators when it comes to overriding hooks or similar. We can attempt to make a decision or just close the issue until someone brings this up again. The reason why nobody has done it so far is probably because integrating backward compatibility is absolutely insane on this one.

**Comment by carmocca** [comment]
If you don't mind, can you open a separate issue for just that so we close this one?

>  because integrating backward compatibility is absolutely insane on this one.

In the new issue, can you broadly describe what would be the pattern used to keep backwards compatibility?

**Comment by awaelchli** [comment]
Follow up #12025
