### ISSUE TITLE
TODO tracker for ongoing training loop refactors

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#7938]
## 📚 TODOs around the loop refactor

This issue tracks the work planned for and after the loop refactor #7700. 
Core contributors feel free to update the description here directly.

### Hygiene and code quality

- [ ] Typing for full mypy compatibility (see ignored files in setup.cfg)
- [x] Documentation for the public interface + address https://github.com/PyTorchLightning/pytorch-lightning/pull/8065#discussion_r656160991
- [x] Evaluate which methods should be public and which should be protected
- [x] Rename Trainer.train_loop to Trainer.fit_loop and deprecate the former access. 
- [x] Formalize how arguments are forwarded to lower loops (especially in `connect`

### Feature integration and follow-up refactors
- [x] Extract a OptimizerLoop, potentially a loop for TBPTT  #9191
    - [x] extract utility for `_run_optimization` 
    - [x] for manual optimization, replace closure call with direct call to `_training_step()`
- [x] Integrate progress tracking #6429, this will also increase clarity and minimize attack surface for bugs!
- [x] Determine who should own the dataloaders and responsibility of resetting them https://github.com/PyTorchLightning/pytorch-lightning/pull/7871#discussion_r649680923. Can references fall out of sync? https://github.com/PyTorchLightning/pytorch-lightning/pull/7871#discussion_r649680539
- [x] Add a teardown, let loops move their results to CPU instead of LoggerConnector: https://github.com/PyTorchLightning/pytorch-lightning/pull/8245
- [x] The `EvaluationDataLoaderLoop.predictions` are currently accumulated inside the inner evaluation loop instead of per epoch and then combined over all dataloaders. #8850 
- [x] Rename inner loops to epoch_loop, batch_loope etc to distinguish top level loop access. Also propose file structure organizing these. Resolved by #8077

### Customization
- [x] Formalize how loops get instantiated, set on the trainer, and connected to each other. #8226 

### Miscellaneous
- Several todo's are annotated as TODO(@awaelchli) 
- Some todo's are annotated as TODO(@justusschock) as well. 

cc: @justusschock @carmocca @ananthsub @tchaton

**Comment by carmocca** [comment]
Closing as everything looks done here
