### ISSUE TITLE
TODOs for achieving stability for Trainer Strategy API

### ISSUE THREAD

**Issue by kaushikb11** [PyTorchLightning/pytorch-lightning#9932]
### Motivation

We have added the `strategy` argument for Trainer in [this](https://github.com/PyTorchLightning/pytorch-lightning/pull/8597) PR.

### The next immediate refactors required are:
- [x] Tests #9931 
- [x] Code/warnings updates #9937 
- [x] Docs: general usage #10000 
- [x] Docs: Trainer flag documentation (accelerator, strategy) #10042 
- [x] tutorials

### Post the above refactors, we will be going through the below internal updates:

- [x]  Remove DistributedType.DDP_CPU. This should not be a valid `strategy` value.
- [x]  Remove DistributedType.TPU_SPAWN
- [x]  Rename DistributedType to StrategyType #10505
- [x]  Rename DeviceType to AcceleratorType #10503 
- [x]  Remove user-facing distributed_backend references in code and error messages. #10017
- [x]  Rename the inernal `self.distributed_backend` references.
- [x]  Rename AcceleratorConnector._device_type to _accelerator_type
- [x]  Rename AcceleratorConnector._distrib_type to _strategy_type
- [ ]  Define all non-supported accelerator-strategy combinations. Is this already done?
- [x]  Rename TrainingTypePlugin and its references to StrategyPlugin #10548 
- [ ] Remove "test_accelerator_x" tests in `tests/accelerators/test_accelerator_connector.py` that test for the deprecated usage of `accelerator="strategy_name"`

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by daniellepintz** [comment]
Do we want to also rename DeviceType here to AcceleratorType?
https://github.com/PyTorchLightning/pytorch-lightning/blob/7b4df7bf919acfd7f7b39d780faeadb54aec9ade/pytorch_lightning/utilities/enums.py#L114
